# Generated by Django 4.1.7 on 2023-04-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectmakandura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_project_m', models.CharField(max_length=200)),
                ('summery_project_m', models.TextField()),
                ('content_project_m', models.JSONField()),
                ('image_project_m', models.CharField(max_length=200)),
            ],
        ),
    ]
