# Generated by Django 4.1.7 on 2023-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMakandura', '0004_projectmakandura_content_project_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmakandura',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectmakandura',
            name='content_project_m',
            field=models.JSONField(),
        ),
    ]
