# Generated by Django 4.1.7 on 2023-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='content',
            new_name='content_pastevent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_project_m',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='summery',
            new_name='summery_pastevent',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='title_pastevent',
        ),
        migrations.AddField(
            model_name='event',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
