# Generated by Django 4.1.7 on 2023-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMakandura', '0002_remove_projectmakandura_content_project_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmakandura',
            name='summery_project_m',
            field=models.TextField(),
        ),
    ]
