# Generated by Django 4.1.7 on 2023-04-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMakandura', '0003_alter_projectmakandura_summery_project_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmakandura',
            name='content_project_m',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectmakandura',
            name='image_project_m',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
