# Generated by Django 4.1.7 on 2023-06-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectMakandura', '0005_projectmakandura_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmakandura',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
