# Generated by Django 4.1.7 on 2023-05-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
