# Generated by Django 4.1.7 on 2023-06-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='summery',
            new_name='summary',
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
