# Generated by Django 4.1.7 on 2023-06-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_summery_news_summary_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
